export const ROUTES = {
  DASHBOARD: '/',
  CLIENTES: '/clientes',
  ORDENES: '/ordenes',
  INVENTARIO: '/inventario',
  OPERACIONES: '/operaciones',
  FACTURACION: '/facturacion',
  REPORTES: '/reportes',
  USUARIOS: '/usuarios',
  PARAMETROS: '/parametros',
  CONFIGURACION: '/configuracion',
  SOPORTE: '/soporte',
  /** Incremento 2 — vistas por CU (informe) */
  CU147: '/operaciones/cu-147',
  CU148: '/operaciones/cu-148',
  CU155: '/operaciones/cu-155',
  CU156: '/operaciones/cu-156',
  CU157: '/operaciones/cu-157',
  CU158: '/reportes/cu-158',
  CU159: '/reportes/cu-159',
  FORGOT_PASSWORD: '/recuperar-contrasena',
  RESET_PASSWORD: '/restablecer-contrasena',
  LOGIN_SUCCESS: '/login-exitoso',
} as const
